name: compile

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile EA
        uses: fx31337/mql-compile-action@v2
        with:
          path: 'XAUUSD_EMA_RSI_ATR_EA.mq5'
          include: '.'
          init-platform: true
          mt-version: '5.0.0.3815'
          log-file: 'compile.log'
          verbose: true

      - name: Show compile log
        if: always()
        run: Get-Content compile.log
        shell: pwsh
