name: Compile MQL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile MQL Code
        uses: fx31337/mql-compile-action@v2
        with:
          init-platform: true
          # Specify path if your files are in a subfolder (e.g., 'Experts/MyRobot.mq4')
          # path: '.' 
